steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Ensure Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create flask-terraform --repository-format=docker --location=us-central1

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-terraform/flask-app:latest', 
      './app'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to Registry'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/flask-terraform/flask-app:latest'
    ]

  - name: 'hashicorp/terraform:1.6.0'
    id: 'Terraform Init'
    dir: 'terraform'
    args: ['init']

  - name: 'hashicorp/terraform:1.6.0'
    id: 'Terraform Apply'
    dir: 'terraform'
    args: [
      'apply', 
      '-var=project_id=$PROJECT_ID',
      '-auto-approve'
    ]

options:
  logging: CLOUD_LOGGING_ONLY